### ISSUE TITLE
Document USB Host with power through VIN

### ISSUE THREAD

**Issue by sebromero** [arduino/arduino-pro-content#17]
For the case that someone doesn't have a USB hub we shall document how to run the USB host example without it just by powering the board through VIN and connecting a keyboard to the USB port.
In that case power needs to be fed to the USB port. This can be enabled like this:

`mbed::DigitalOut otg(PJ_6, 0); //Provide power to the USB when powered through VIN`

UPDATE: Turn this into a nicer API and document that one. See comments below.

**Comment by facchinm** [comment]
It's probably a better idea to hide this inside USBHost library (with an API like `enableVbus()`)

**Comment by sbhklr** [comment]
@facchinm Good call! Let's do that. I'll give the USB API a shot as soon as I have some capacity.
